apiVersion: k0s.k0sproject.io/v1beta1
kind: ClusterConfig
metadata:
  creationTimestamp: null
  name: k0s
spec:
  api:
    address: 172.17.0.1
    k0sApiPort: 9443
    port: 6443
    sans:
    - 172.17.0.1
    - 192.168.1.20
    - fe80::42:f9ff:fee1:23d7
    - fe80::7c99:aaff:fe85:8c0e
    - fe80::8c83:1bff:fe56:5dcc
  controllerManager: {}
  extensions:
    helm:
      concurrencyLevel: 5
      repositories:
      charts:
    storage:
      create_default_storage_class: false
      type: external_storage
  # NOTE: ON PRODUCTION THIS WILL BE ENABLED, SO THAT THE LOCAL IMAGES WILL BE USED
  # images:
  #   default_pull_policy: Never
  installConfig:
    users:
      etcdUser: etcd
      kineUser: kube-apiserver
      konnectivityUser: konnectivity-server
      kubeAPIserverUser: kube-apiserver
      kubeSchedulerUser: kube-scheduler
  konnectivity:
    adminPort: 8133
    agentPort: 8132
  network:
    calico: null
    clusterDomain: cluster.local
    dualStack: {}
    kubeProxy:
      iptables:
        minSyncPeriod: 0s
        syncPeriod: 0s
      ipvs:
        minSyncPeriod: 0s
        syncPeriod: 0s
        tcpFinTimeout: 0s
        tcpTimeout: 0s
        udpTimeout: 0s
      metricsBindAddress: 0.0.0.0:10249
      mode: iptables
    kuberouter:
      autoMTU: true
      hairpin: Enabled
      ipMasq: false
      metricsPort: 8080
      mtu: 0
      peerRouterASNs: ""
      peerRouterIPs: ""
    nodeLocalLoadBalancing:
      envoyProxy:
        apiServerBindPort: 7443
        konnectivityServerBindPort: 7132
      type: EnvoyProxy
    podCIDR: 10.244.0.0/16
    provider: kuberouter
    serviceCIDR: 10.96.0.0/12
  scheduler: {}
  storage:
    etcd:
      externalCluster: null
      peerAddress: 172.17.0.1
    type: etcd
  telemetry:
    enabled: false
