version: '3.6'
services:
  gitlab:
    image: gitlab/gitlab-ce:17.0.0-ce.0
    container_name: gitlab
    restart: always
    hostname: 'gitlab.local'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'https://gitlab.local'
    ports:
      - '80:80'
      - '443:443'
      - '2222:22'
    volumes:
      - '/home/viruzeno/gitlab/config:/etc/gitlab'
      - '/home/viruzeno/gitlab/logs:/var/log/gitlab'
      - '/home/viruzeno/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
