apiVersion: v1
kind: Pod
metadata:
  name: host-network-pod
spec:
  hostNetwork: true
  containers:
  - name: my-container
    image: nginx:latest
    ports:
    - containerPort: 80
      hostPort: 80