---
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab-system
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  # Ensure this value matches `spec.chart.values.global.ingress.class`
  name: gitlab-nginx
  namespace: gitlab-system
spec:
  controller: k8s.io/ingress-nginx