apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
spec:
  chart:
    version: "7.11.2" # https://gitlab.com/gitlab-org/cloud-native/gitlab-operator
    values:
      certmanager:
        install: false
      nginx-ingress:
        enabled: false
      global:
        hosts:
          domain: gitlab.local
        ingress:
          configureCertmanager: true
      certmanager-issuer:
        email: viruzeno@gmail.com

# apiVersion: apps.gitlab.com/v1beta1
# kind: GitLab
# metadata:
#   name: gitlab
#   namespace: gitlab-system
# spec:
#   chart:
#     values:
#       certmanager:
#         install: false
#       global:
#         hosts:
#           domain: gitlab.local
#           hostSuffix: null
#         ingress:
#           configureCertmanager: false
#           tls:
#             secretName: null
#     version: ''