---
apiVersion: v1
kind: Namespace
metadata:
  name: test

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: docker.io/bashofmann/rancher-demo:1.0.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "12Mi"
              cpu: "2m"
          ports:
            - containerPort: 8080
              name: web
              protocol: TCP
          env:
            - name: COW_COLOR
              value: purple
          readinessProbe:
            httpGet:
              path: /
              port: web
          livenessProbe:
            httpGet:
              path: /
              port: web

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: test
spec:
  type: ClusterIP
  selector:
    app: hello-world
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service-loadbalancing
  namespace: test
spec:
  type: LoadBalancer
  selector:
    app: hello-world
  ports:
    - port: 8080
      targetPort: 8080