apiVersion: v1
kind: Pod
metadata:
  name: hostnetwork-pod
spec:
  hostNetwork: true
  containers:
  - name: busybox-container
    image: busybox
    command: ["sh", "-c", "sleep 3600"]  # Keeps the pod alive for 1 hour
    stdin: true
    tty: true