# https://splunk.github.io/splunk-operator/Examples.html
---
apiVersion: enterprise.splunk.com/v4
kind: ClusterManager
metadata:
  name: rke
  namespace: splunk-operator
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  imagePullPolicy: IfNotPresent
  etcVolumeStorageConfig:
    storageCapacity: 15Gi
  varVolumeStorageConfig:
    storageCapacity: 25Gi
  resources:
    requests:
      memory: "8Gi"
      cpu: "6"
    limits:
      memory: "8Gi"
      cpu: "6" 
  monitoringConsoleRef:
    name: rke
  # licenseManagerRef:
  #   name: rke
  # fsGroupChangePolicy: "OnRootMismatch"
---
apiVersion: enterprise.splunk.com/v4
kind: MonitoringConsole
metadata:
  name: rke
  namespace: splunk-operator
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  imagePullPolicy: IfNotPresent
  etcVolumeStorageConfig:
    storageCapacity: 15Gi
  varVolumeStorageConfig:
    storageCapacity: 25Gi
  resources:
    requests:
      memory: "8Gi"
      cpu: "6"
    limits:
      memory: "8Gi"
      cpu: "6" 
  # pod:
  #   securityContext:
  #     seLinuxOptions:
  #       level: "s0:c123,c456"
---
apiVersion: enterprise.splunk.com/v4
kind: IndexerCluster
metadata:
  name: rke
  namespace: splunk-operator
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  imagePullPolicy: IfNotPresent
  etcVolumeStorageConfig:
    storageCapacity: 15Gi
  varVolumeStorageConfig:
    storageCapacity: 25Gi
  resources:
    requests:
      memory: "8Gi"
      cpu: "6"
    limits:
      memory: "8Gi"
      cpu: "6" 
  clusterManagerRef:
    name: rke
  replicas: 2
  monitoringConsoleRef:
    name: monitor
  # pod:
  #   securityContext:
  #     seLinuxOptions:
  #       level: "s0:c123,c456"
---
apiVersion: enterprise.splunk.com/v4
kind: Standalone
metadata:
  name: rke
  namespace: splunk-operator
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  imagePullPolicy: IfNotPresent
  etcVolumeStorageConfig:
    storageCapacity: 15Gi
  varVolumeStorageConfig:
    storageCapacity: 25Gi
  resources:
    requests:
      memory: "8Gi"
      cpu: "6"
    limits:
      memory: "8Gi"
      cpu: "6" 
  clusterManagerRef:
    name: rke
  monitoringConsoleRef:
    name: rke
  # pod:
  #   securityContext:
  #     seLinuxOptions:
  #       level: "s0:c123,c456"
# ---
# apiVersion: enterprise.splunk.com/v4
# kind: LicenseManager
# metadata:
#   name: rke
#   namespace: splunk-operator
#   finalizers:
#   - enterprise.splunk.com/delete-pvc
# spec:
#   volumes:
#     - name: licenses
#       configMap:
#         name: splunk-licenses
#   licenseUrl: /mnt/licenses/enterprise.lic