# https://splunk.github.io/splunk-operator/Examples.html
---
apiVersion: enterprise.splunk.com/v4
kind: ClusterManager
metadata:
  name: rke
  namespace: splunk-operator
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  monitoringConsoleRef:
    name: rke
  # licenseManagerRef:
  #   name: rke
---
apiVersion: enterprise.splunk.com/v4
kind: MonitoringConsole
metadata:
  name: rke
  namespace: splunk-operator
  finalizers:
  - enterprise.splunk.com/delete-pvc
---
apiVersion: enterprise.splunk.com/v4
kind: IndexerCluster
metadata:
  name: rke
  namespace: splunk-operator
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  spec:
  clusterManagerRef:
    name: rke
  replicas: 2
  monitoringConsoleRef:
    name: monitor
---
apiVersion: enterprise.splunk.com/v4
kind: Standalone
metadata:
  name: rke
  namespace: splunk-operator
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  clusterManagerRef:
    name: rke
  monitoringConsoleRef:
    name: rke
# ---
# apiVersion: enterprise.splunk.com/v4
# kind: LicenseManager
# metadata:
#   name: rke
#   namespace: splunk-operator
#   finalizers:
#   - enterprise.splunk.com/delete-pvc
# spec:
#   volumes:
#     - name: licenses
#       configMap:
#         name: splunk-licenses
#   licenseUrl: /mnt/licenses/enterprise.lic