# https://splunk.github.io/splunk-operator/Examples.html
# https://splunk.github.io/splunk-operator/CustomResources.html
# https://github.com/splunk/splunk-ansible/blob/develop/docs/advanced/default.yml.spec.md
---
apiVersion: enterprise.splunk.com/v4
kind: ClusterManager
metadata:
  name: rke
  namespace: splunk-operator
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  imagePullPolicy: IfNotPresent
  etcVolumeStorageConfig:
    storageCapacity: 15Gi
  varVolumeStorageConfig:
    storageCapacity: 25Gi
  resources:
    requests:
      memory: "4Gi"
      cpu: "1"
    limits:
      memory: "8Gi"
      cpu: "4" 
  monitoringConsoleRef:
    name: rke
  # licenseManagerRef:
  #   name: rke
---
apiVersion: enterprise.splunk.com/v4
kind: MonitoringConsole
metadata:
  name: rke
  namespace: splunk-operator
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  imagePullPolicy: IfNotPresent
  etcVolumeStorageConfig:
    storageCapacity: 15Gi
  varVolumeStorageConfig:
    storageCapacity: 25Gi
  resources:
    requests:
      memory: "4Gi"
      cpu: "1"
    limits:
      memory: "8Gi"
      cpu: "4" 
---
apiVersion: enterprise.splunk.com/v4
kind: IndexerCluster
metadata:
  name: rke
  namespace: splunk-operator
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  imagePullPolicy: IfNotPresent
  etcVolumeStorageConfig:
    storageCapacity: 15Gi
  varVolumeStorageConfig:
    storageCapacity: 25Gi
  resources:
    requests:
      memory: "4Gi"
      cpu: "1"
    limits:
      memory: "8Gi"
      cpu: "4" 
  clusterManagerRef:
    name: rke
  replicas: 2
  monitoringConsoleRef:
    name: monitor
---
apiVersion: enterprise.splunk.com/v4
kind: Standalone
metadata:
  name: rke
  namespace: splunk-operator
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  imagePullPolicy: IfNotPresent
  etcVolumeStorageConfig:
    storageCapacity: 15Gi
  varVolumeStorageConfig:
    storageCapacity: 25Gi
  # defaults:
  resources:
    requests:
      memory: "4Gi"
      cpu: "1"
    limits:
      memory: "8Gi"
      cpu: "4" 
  clusterManagerRef:
    name: rke
  monitoringConsoleRef:
    name: rke
# ---
# apiVersion: enterprise.splunk.com/v4
# kind: LicenseManager
# metadata:
#   name: rke
#   namespace: splunk-operator
#   finalizers:
#   - enterprise.splunk.com/delete-pvc
# spec:
#   volumes:
#     - name: licenses
#       configMap:
#         name: splunk-licenses
#   licenseUrl: /mnt/licenses/enterprise.lic